<?php
namespace App\Services;

class SettingService {

    public static function appInformations($app_info) {
        $data = [
            'is_production'                   => $app_info['is_production'],
            'name_ar'                         => $app_info['name_ar'],
            'name_en'                         => $app_info['name_en'],
            'email'                           => $app_info['email'],
            'phone'                           => $app_info['phone'],
            'whatsapp'                        => $app_info['whatsapp'],
            'terms_ar'                        => $app_info['terms_ar'],
            'terms_en'                        => $app_info['terms_en'],
            'terms_kur'                       => $app_info['terms_kur'],
            'about_ar'                        => $app_info['about_ar'],
            'about_en'                        => $app_info['about_en'],
            'about_kur'                       => $app_info['about_kur'],
            'how_work_ar'                     => $app_info['how_work_ar'],
            'how_work_en'                     => $app_info['how_work_en'],
            'how_work_kur'                    => $app_info['how_work_kur'],
            'logo'                            => ('/storage/images/settings/' . $app_info['logo']),
            'fav_icon'                        => ('/storage/images/settings/' . $app_info['fav_icon']),
            'no_data_icon'                    => $app_info['no_data_icon'],
            'default_user'                    => ('/storage/images/users/' . $app_info['default_user']),
            'default_image'                   => ("/defaults/" . $app_info['default_user']),
            'login_background'                => ('/storage/images/settings/' . $app_info['login_background']),
            'intro_logo'                      => ('/storage/images/settings/' . $app_info['intro_logo']),
            'intro_loader'                    => ('/storage/images/settings/' . $app_info['intro_loader']),
            'intro_name'                      => $app_info['intro_name_' . lang()],
            'intro_name_ar'                   => $app_info['intro_name_ar'],
            'intro_name_en'                   => $app_info['intro_name_en'],
            'intro_about'                     => $app_info['intro_about_' . lang()],
            'intro_about_ar'                  => $app_info['intro_about_ar'],
            'intro_about_en'                  => $app_info['intro_about_en'],
            'privacy_ar'                      => $app_info['privacy_ar'],
            'privacy_en'                      => $app_info['privacy_en'],
            'about_image_2'                   => ('/storage/images/settings/' . $app_info['about_image_2']),
            'about_image_1'                   => ('/storage/images/settings/' . $app_info['about_image_1']),
            'services_text_ar'                => $app_info['services_text_ar'],
            'services_text_en'                => $app_info['services_text_en'],
            'services_text'                   => $app_info['services_text_' . lang()],
            'how_work_text_ar'                => $app_info['how_work_text_ar'],
            'how_work_text_en'                => $app_info['how_work_text_en'],
            'how_work_text'                   => $app_info['how_work_text_' . lang()],
            'fqs_text_ar'                     => $app_info['fqs_text_ar'],
            'fqs_text_en'                     => $app_info['fqs_text_en'],
            'fqs_text'                        => $app_info['fqs_text_' . lang()],
            'parteners_text_ar'               => $app_info['parteners_text_ar'],
            'parteners_text_en'               => $app_info['parteners_text_en'],
            'parteners_text'                  => $app_info['parteners_text_' . lang()],
            'contact_text_ar'                 => $app_info['contact_text_ar'],
            'contact_text_en'                 => $app_info['contact_text_en'],
            'contact_text'                    => $app_info['contact_text_' . lang()],
            'intro_email'                     => $app_info['intro_email'],
            'intro_phone'                     => $app_info['intro_phone'],
            'intro_address'                   => $app_info['intro_address'],
            'color'                           => $app_info['color'],
            'buttons_color'                   => $app_info['buttons_color'],
            'hover_color'                     => $app_info['hover_color'],
            'intro_meta_description'          => $app_info['intro_meta_description'],
            'intro_meta_keywords'             => $app_info['intro_meta_keywords'],

            'smtp_user_name'                  => $app_info['smtp_user_name'],
            'smtp_password'                   => $app_info['smtp_password'],
            'smtp_mail_from'                  => $app_info['smtp_mail_from'],
            'smtp_sender_name'                => $app_info['smtp_sender_name'],
            'smtp_port'                       => $app_info['smtp_port'],
            'smtp_host'                       => $app_info['smtp_host'],
            'smtp_encryption'                 => $app_info['smtp_encryption'],

            'admin_commission_ratio'          => $app_info['admin_commission_ratio'],
            'vat_rate_ratio'                  => $app_info['vat_rate_ratio'],
            'reservation_price'               => $app_info['reservation_price'],

            'firebase_key'                    => $app_info['firebase_key'],
            'firebase_sender_id'              => $app_info['firebase_sender_id'],

            'google_places'                   => $app_info['google_places'],
            'google_analytics'                => $app_info['google_analytics'],
            'live_chat'                       => $app_info['live_chat'],

            'lab_header_title_ar'             => $app_info['lab_header_title_ar'],
            'lab_header_title_en'             => $app_info['lab_header_title_en'],
            'lab_header_title_kur'            => $app_info['lab_header_title_kur'],
            'lab_header_description_ar'       => $app_info['lab_header_description_ar'],
            'lab_header_description_en'       => $app_info['lab_header_description_en'],
            'lab_header_description_kur'      => $app_info['lab_header_description_kur'],
            'doctor_header_title_ar'          => $app_info['doctor_header_title_ar'],
            'doctor_header_title_en'          => $app_info['doctor_header_title_en'],
            'doctor_header_title_kur'         => $app_info['doctor_header_title_kur'],
            'doctor_header_description_ar'    => $app_info['doctor_header_description_ar'],
            'doctor_header_description_en'    => $app_info['doctor_header_description_en'],
            'doctor_header_description_kur'   => $app_info['doctor_header_description_kur'],
            'store_header_title_ar'           => $app_info['store_header_title_ar'],
            'store_header_title_en'           => $app_info['store_header_title_en'],
            'store_header_title_kur'          => $app_info['store_header_title_kur'],
            'store_header_description_ar'     => $app_info['store_header_description_ar'],
            'store_header_description_en'     => $app_info['store_header_description_en'],
            'store_header_description_kur'    => $app_info['store_header_description_kur'],
            'pharmacy_header_title_ar'        => $app_info['pharmacy_header_title_ar'],
            'pharmacy_header_title_en'        => $app_info['pharmacy_header_title_en'],
            'pharmacy_header_title_kur'       => $app_info['pharmacy_header_title_kur'],
            'pharmacy_header_description_ar'  => $app_info['pharmacy_header_description_ar'],
            'pharmacy_header_description_en'  => $app_info['pharmacy_header_description_en'],
            'pharmacy_header_description_kur' => $app_info['pharmacy_header_description_kur'],
            'most_famous_doctors_text_ar'     => $app_info['most_famous_doctors_text_ar'],
            'most_famous_doctors_text_en'     => $app_info['most_famous_doctors_text_en'],
            'most_famous_doctors_text_kur'    => $app_info['most_famous_doctors_text_kur'],
            'google_play_link'                => $app_info['google_play_link'],
            'app_store_link'                  => $app_info['app_store_link'],
            'platform_explain_link'           => $app_info['platform_explain_link'],

            'join_doctor_text_ar'             => $app_info['join_doctor_text_ar'],
            'join_doctor_text_en'             => $app_info['join_doctor_text_en'],
            'join_doctor_text_kur'            => $app_info['join_doctor_text_kur'],
            'join_pharmacy_text_ar'           => $app_info['join_pharmacy_text_ar'],
            'join_pharmacy_text_en'           => $app_info['join_pharmacy_text_en'],
            'join_pharmacy_text_kur'          => $app_info['join_pharmacy_text_kur'],
            'join_lab_text_ar'                => $app_info['join_lab_text_ar'],
            'join_lab_text_en'                => $app_info['join_lab_text_en'],
            'join_lab_text_kur'               => $app_info['join_lab_text_kur'],
            'join_store_text_ar'              => $app_info['join_store_text_ar'],
            'join_store_text_en'              => $app_info['join_store_text_en'],
            'join_store_text_kur'             => $app_info['join_store_text_kur'],
            'reservations_number_per_day'     => $app_info['reservations_number_per_day'],
            'store_delivery_price'            => $app_info['store_delivery_price'],

            'vat_ratio'                       => $app_info['vat_ratio'],
        ];
        return $data;
    }

}
