@include('providers_dashboards.layouts.dashboards.header')
@include('providers_dashboards.layouts.dashboards.sidebar')
@include('providers_dashboards.layouts.dashboards.nav')
    @yield('content')
@include('providers_dashboards.layouts.dashboards.footer')